// Generated by CoffeeScript 1.7.1
(function() {
  window.main = {
    init: function() {
      return main.dfpOrders();
    },
    dfpOrders: function() {
      $('#orders').change(function() {
        var order_id;
        order_id = $(this).val();
        $('#name_order').val($("#orders option:selected").text());
        return $.ajax({
          url: APP_JQ + "/admin/sites/getlinesitems",
          type: "POST",
          data: "order_id=" + order_id,
          beforeSend: function() {
            return $('.load_lines').show();
          },
          success: function(results) {
            $('.load_lines').hide();
            if (results !== "") {
              return $('#line_items').empty().html(results);
            } else {
              return alert("error al obtener lineas de pedido");
            }
          }
        });
      });
      $('.adunit_sel').change(function() {
        var id_adunit, name_adunit;
        id_adunit = $(this).attr("id");
        name_adunit = $("#" + id_adunit + " option:selected").text();
        return $(this).next().val(name_adunit);
      });
      $('.adunit_sel_single').change(function() {
        var id_adunit, name_adunit;
        id_adunit = $(this).attr("id");
        name_adunit = $("#" + id_adunit + " option:selected").text();
        return $("#ZonaAdunitName").val(name_adunit);
      });
      $('#line_items').change(function() {
        return $('#name_lineitem').val($("#line_items option:selected").text());
      });
      $('.checkemail').change(function() {
        var email;
        email = $(this).val();
        if (email === "") {
          return false;
        }
        return $.ajax({
          url: APP_JQ + "/admin/users/checkemail",
          type: "POST",
          data: "email=" + email,
          beforeSend: function() {
            $('.check_email').empty().html("Revisando disponibilidad de correo.").show();
            return $('input[type="submit"]').attr('disabled', 'disabled').css('opacity', '.5');
          },
          success: function(results) {
            if (results === "1") {
              $('.check_email').hide().empty();
              return $('input[type="submit"]').removeAttr('disabled').css('opacity', '1');
            } else {
              return $('.check_email').empty().html("El correo ingresado ya se encuentra utilizado.").show();
            }
          }
        });
      });
      $("#newZona").click(function() {
        var self;
        self = $(this);
        $.ajax({
          url: APP_JQ + "/admin/plugins/addzona",
          type: "GET",
          data: "",
          beforeSend: function() {
            $('.wait-agregar').show();
            return self.prop('disabled', true);
          },
          success: function(results) {
            $('.addZona').append(results);
            $('.wait-agregar').hide();
            return self.prop('disabled', false);
          },
          fail: function() {
            self.prop('disabled', false);
            return alert('Error, favor intentar nuevamente');
          }
        });
        return false;
      });
      $(document).on("click", ".removeRow", function() {
        return $(this).parent().parent().remove();
      });
      $(document).on("click", ".zonaDelete", function() {
        var zona;
        zona = $(this);
        return $.ajax({
          url: APP_JQ + "/admin/zonas/delete_async/" + zona.attr('data-zona'),
          type: "POST",
          data: "",
          beforeSend: function() {},
          success: function(results) {
            if (results.response !== "1") {
              return zona.parent().parent().remove();
            } else {
              return alert("error al eliminar zona");
            }
          }
        });
      });
      return $(document).on("change", ".selectedLine", function() {
        var adunits, selectTarget, waitSelected;
        adunits = $(this);
        selectTarget = adunits.parent().parent().next().find('select');
        waitSelected = adunits.parent().parent().next().find('.wait-select');
        return $.ajax({
          url: APP_JQ + "/admin/plugins/getadunits",
          type: "POST",
          data: "adunits=" + adunits.val(),
          beforeSend: function() {
            waitSelected.show();
            return selectTarget.hide();
          },
          success: function(results) {
            waitSelected.hide();
            selectTarget.show();
            if (results !== "") {
              return selectTarget.empty().html(results);
            } else {
              return alert("error al obtener lineas de pedido");
            }
          }
        });
      });
    }
  };

  $('document').ready(function() {
    return window.main.init();
  });

}).call(this);
